version: '2'
services:    
    elastalert:
        build: .
        environment:
            ELASTIC_PWD: changeme
            ELASTICSEARCH_HOST: ip172-18-0-50-bso348boudsg008te3dg-9200.direct.labs.play-with-docker.com
            ELASTICSEARCH_PORT: 80
        volumes:
            - ./elastalert:/etc/elastalert
            - ./rules:/usr/share/elastalert/rules
        network_mode: bridge
        restart: unless-stopped
